### ISSUE TITLE
Kindly create new release for this dataset.

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Lichenous#3]
Hey @millerse - 

Now that this dataset is published on zenodo, GloBI will pick the uncorrected one on zenodo, instead of the (corrected) latest commit on github. 

Suggest to:
1. create a new release on github
2. go to zenodo and request the release to be added to the globalbioticinteractions community.

Thanks & let me know if you have any questions / concerns.

**Comment by millerse** [comment]
@jhpoelen Got it.

**Comment by jhpoelen** [comment]
Thanks for releasing a new version!
